### ISSUE TITLE
Do not require perl 5.12

### ISSUE THREAD

**Issue by bjakubski** [jonasbn/testt#3] opened 2015-07-07 09:14 UTC
With 0.10 release it seems perl version requirement was bumped to 5.12. As someone working on 5.10 perl this poses a bit of a problem to me.
It seems to me that maybe that bump was accidental? There is no mention of that in Changes file.
Also info in metadata is somewhat contradictory - dist.ini specifies 5.12 and that version is required to run Makefile.PL, but META.json shipped to cpan with 0.10 contains runtime perl 5.10 requirement...

**Comment by jonasbn** [comment] 2015-07-15 17:37
I checked using Perl::Minimum version and it should be sufficient with Perl 5.6.0, I will investigate and make a bug fix release based on my findings, I will keep you in the loop - thanks for the bug report.

**Comment by jonasbn** [comment] 2015-07-15 18:26
Should be resolved in release 0.11, just uploaded to CPAN - again, thanks for the bug report and sorry for any inconvenience caused by the change introduced in 0.10

**Closed by jonasbn** 2015-07-15 18:26 UTC
Labels: bug
